// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/streamssn.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_proto_streamssn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streamssn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_proto_streamssn_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *AudioChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Transcript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp     float32                `protobuf:"fixed32,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transcript) Reset() {
	*x = Transcript{}
	mi := &file_proto_streamssn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transcript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transcript) ProtoMessage() {}

func (x *Transcript) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streamssn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transcript.ProtoReflect.Descriptor instead.
func (*Transcript) Descriptor() ([]byte, []int) {
	return file_proto_streamssn_proto_rawDescGZIP(), []int{1}
}

func (x *Transcript) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Transcript) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Transcript) GetTimestamp() float32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_streamssn_proto protoreflect.FileDescriptor

const file_proto_streamssn_proto_rawDesc = "" +
	"\n" +
	"\x15proto/streamssn.proto\x12\tstreamssn\"J\n" +
	"\n" +
	"AudioChunk\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"]\n" +
	"\n" +
	"Transcript\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x02R\ttimestamp2L\n" +
	"\tStreamASR\x12?\n" +
	"\vStreamAudio\x12\x15.streamssn.AudioChunk\x1a\x15.streamssn.Transcript(\x010\x01B\vZ\t/proto;pbb\x06proto3"

var (
	file_proto_streamssn_proto_rawDescOnce sync.Once
	file_proto_streamssn_proto_rawDescData []byte
)

func file_proto_streamssn_proto_rawDescGZIP() []byte {
	file_proto_streamssn_proto_rawDescOnce.Do(func() {
		file_proto_streamssn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_streamssn_proto_rawDesc), len(file_proto_streamssn_proto_rawDesc)))
	})
	return file_proto_streamssn_proto_rawDescData
}

var file_proto_streamssn_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_streamssn_proto_goTypes = []any{
	(*AudioChunk)(nil), // 0: streamssn.AudioChunk
	(*Transcript)(nil), // 1: streamssn.Transcript
}
var file_proto_streamssn_proto_depIdxs = []int32{
	0, // 0: streamssn.StreamASR.StreamAudio:input_type -> streamssn.AudioChunk
	1, // 1: streamssn.StreamASR.StreamAudio:output_type -> streamssn.Transcript
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_streamssn_proto_init() }
func file_proto_streamssn_proto_init() {
	if File_proto_streamssn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_streamssn_proto_rawDesc), len(file_proto_streamssn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_streamssn_proto_goTypes,
		DependencyIndexes: file_proto_streamssn_proto_depIdxs,
		MessageInfos:      file_proto_streamssn_proto_msgTypes,
	}.Build()
	File_proto_streamssn_proto = out.File
	file_proto_streamssn_proto_goTypes = nil
	file_proto_streamssn_proto_depIdxs = nil
}
