// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/streamssn.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamASR_StreamAudio_FullMethodName = "/streamssn.StreamASR/StreamAudio"
)

// StreamASRClient is the client API for StreamASR service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamASRClient interface {
	StreamAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, Transcript], error)
}

type streamASRClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamASRClient(cc grpc.ClientConnInterface) StreamASRClient {
	return &streamASRClient{cc}
}

func (c *streamASRClient) StreamAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, Transcript], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamASR_ServiceDesc.Streams[0], StreamASR_StreamAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, Transcript]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamASR_StreamAudioClient = grpc.BidiStreamingClient[AudioChunk, Transcript]

// StreamASRServer is the server API for StreamASR service.
// All implementations must embed UnimplementedStreamASRServer
// for forward compatibility.
type StreamASRServer interface {
	StreamAudio(grpc.BidiStreamingServer[AudioChunk, Transcript]) error
	mustEmbedUnimplementedStreamASRServer()
}

// UnimplementedStreamASRServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamASRServer struct{}

func (UnimplementedStreamASRServer) StreamAudio(grpc.BidiStreamingServer[AudioChunk, Transcript]) error {
	return status.Error(codes.Unimplemented, "method StreamAudio not implemented")
}
func (UnimplementedStreamASRServer) mustEmbedUnimplementedStreamASRServer() {}
func (UnimplementedStreamASRServer) testEmbeddedByValue()                   {}

// UnsafeStreamASRServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamASRServer will
// result in compilation errors.
type UnsafeStreamASRServer interface {
	mustEmbedUnimplementedStreamASRServer()
}

func RegisterStreamASRServer(s grpc.ServiceRegistrar, srv StreamASRServer) {
	// If the following call panics, it indicates UnimplementedStreamASRServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamASR_ServiceDesc, srv)
}

func _StreamASR_StreamAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamASRServer).StreamAudio(&grpc.GenericServerStream[AudioChunk, Transcript]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamASR_StreamAudioServer = grpc.BidiStreamingServer[AudioChunk, Transcript]

// StreamASR_ServiceDesc is the grpc.ServiceDesc for StreamASR service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamASR_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streamssn.StreamASR",
	HandlerType: (*StreamASRServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAudio",
			Handler:       _StreamASR_StreamAudio_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/streamssn.proto",
}
